### PR TITLE
Add support for Windows

### PR DESCRIPTION
**Pull request by kjunichi**
Hi, glsl2img is nice!
I try to support for windows.
thank you.

If you use this patch, you have to get GTK 2 bundle for Win32 or Win64. Unzip the contents in C:\GTK.

- http://ftp.gnome.org/pub/GNOME/binaries/win32/gtk+/2.24/gtk+-bundle_2.24.10-20120208_win32.zip
- http://ftp.gnome.org/pub/GNOME/binaries/win64/gtk+/2.22/gtk+-bundle_2.22.1-20101229_win64.zip

### CODE REVIEW

**Comment by fand** [comment]
Thank you for PR!
It's great if Windows users could use glsl2img.

However, I'm little afraid to write OS-specific code by myself.
I'm gonna find some npm package which takes care of enviroments.

**Comment by kjunichi** [comment]
OK.
Thanks for your quick reply.
I understood.

**Comment by fand** [comment]
I've replaced `execFileSync` with [execa](https://github.com/sindresorhus/execa), and added CI configuration with AppVeyor.
I Hope it works out. :) @kjunichi

**Comment by kjunichi** [comment]
it works like a charm.thank you!

**Pull request closed without merging**
